const List<String> moods = [
  "Felice",
  "Allegro",
  "Euforico",
  "Soddisfatto",
  "Entusiasta",
  "Radioso",
  "Spensierato",
  "Sollevato",
  "Appagato",
  "Ottimista",
  "Innamorato",
  "Affettuoso",
  "Tenero",
  "Protettivo",
  "Compassionevole",
  "Empatico",
  "Grato",
  "Fiducioso",
  "Intimo",
  "Serafico",
  "Tranquillo",
  "Rilassato",
  "Pacato",
  "Equilibrato",
  "Meditativo",
  "Riflessivo",
  "Saggio",
  "Sereno",
  "Triste",
  "Depresso",
  "Demoralizzato",
  "Nostalgico",
  "Afflitto",
  "Abbandonato",
  "Sconsolato",
  "Avvilito",
  "Rassegnato",
  "Apatico",
  "Irritato",
  "Arrabbiato",
  "Furioso",
  "Infastidito",
  "Frustrato",
  "Risentito",
  "Vendicativo",
  "Deluso",
  "Esasperato",
  "Ansioso",
  "Preoccupato",
  "Spaventato",
  "Terrorizzato",
  "Inquieto",
  "Nervoso",
  "Allarmato",
  "Sospettoso",
  "Timoroso",
  "Vulnerabile",
  "Confuso",
  "Indeciso",
  "Disorientato",
  "Perplesso",
  "Sconcertato",
  "Annoiato",
  "Indifferente",
  "Svogliato",
  "Stanco",
  "Sorpreso",
  "Stupito",
  "Meravigliato",
  "Scioccato",
  "Incredulo",
  "Invidioso",
  "Geloso",
  "Vergognoso",
  "Imbarazzato",
  "Colpevole",
  "Umiliato",
  "Mortificato",
  "Fiero",
  "Orgoglioso",
  "Arrogante",
  "Presuntuoso",
  "Superbo",
  "Trionfante",
  "Incompreso",
  "Emarginato",
  "Alienato",
  "Commosso",
  "Premuroso",
  "Altruista",
  "Generoso",
  "Speranzoso",
  "Motivato",
  "Incoraggiato",
  "Ispirato",
];

const String autoMood = "<Auto>";
const String uiMaxPosts = "UI_MAX_POSTS";
const String uiMinLength = "UI_MIN_LENGTH";
const String uiMaxLength = "UI_MAX_LENGTH";
const String uiModelTemperature = "UI_MODEL_TEMPERATURE";
const String uiModelTopP = "UI_MODEL_TOP_P";
const String uiDryRun = "UI_DRY_RUN";
const String uiSourceBlog = "UI_SOURCE_BLOG";
const String uiTargetBlog = "UI_TARGET_BLOG";
const String uiModel = "UI_MODEL";
const String uiMood = "UI_MOOD";
const String uiSkipAsks = "UI_SKIP_ASKS";
const String uiSkipTags = "UI_SKIP_TAGS";
