name: Flutter Deskop Deployment

on:
  push:
    branches:
      - desktop
    tags:
      - 'v*.*.*'

jobs:
  linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - name: Install os dependencies
        run: sudo apt-get install -y clang cmake git ninja-build pkg-config libgtk-3-dev liblzma-dev libstdc++-12-dev
      - name: Install project dependencies
        run: flutter pub get || true
      - name: Enable linux build
        run: flutter config --enable-linux-desktop
      - name: Build artifacts
        run: flutter build linux --release --split-debug-info=debugsym --dart-define=CLIENT_ID=${{ secrets.CLIENT_ID }} --dart-define=CLIENT_SECRET=${{ secrets.CLIENT_SECRET }}
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Linux64
          path: build/linux/x64/release/bundle
      - name: Create package folder
        if: startsWith(github.ref, 'refs/tags/')
        run: mkdir package
      - name: Package Release files
        if: startsWith(github.ref, 'refs/tags/')
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          filename: ../../../../../package/TumblrAI-${{github.ref_name}}-Linux64.zip
          directory: build/linux/x64/release/bundle
      - name: Release to github
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        with:
          tag_name: ${{github.ref_name}}
          files: package/TumblrAI-${{github.ref_name}}-Linux64.zip


  windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - name: Install project dependencies
        run: flutter pub get || true
      - name: Enable windows build
        run: flutter config --enable-windows-desktop
      - name: Build artifacts
        run: flutter build windows --release --split-debug-info=debugsym --dart-define=CLIENT_ID=${{ secrets.CLIENT_ID }} --dart-define=CLIENT_SECRET=${{ secrets.CLIENT_SECRET }}
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Windows64
          path: build/windows/x64/runner/Release
      - name: Create package folder
        if: startsWith(github.ref, 'refs/tags/')
        run: mkdir package
      - name: Package Release files
        if: startsWith(github.ref, 'refs/tags/')
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          filename: ../../../../../package/TumblrAI-${{github.ref_name}}-Windows64.zip
          directory: build/windows/x64/runner/Release
      - name: Release to github
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        with:
          tag_name: ${{github.ref_name}}
          files: package/TumblrAI-${{github.ref_name}}-Windows64.zip


  macos:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-13
            arch: Intel
          - os: macos-latest
            arch: ARM

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - name: Install project dependencies
        run: flutter pub get || true
      - name: Enable macos build
        run: flutter config --enable-macos-desktop
      - name: Build artifacts
        run: flutter build macos --release --split-debug-info=debugsym --dart-define=CLIENT_ID=${{ secrets.CLIENT_ID }} --dart-define=CLIENT_SECRET=${{ secrets.CLIENT_SECRET }}
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: MacOS-${{ matrix.arch }} 
          path: build/macos/Build/Products/Release/TumblrAI.app
      - name: Create package folder
        if: startsWith(github.ref, 'refs/tags/')
        run: mkdir package
      - name: Package Release files
        if: startsWith(github.ref, 'refs/tags/')
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          filename: ../../../../../package/TumblrAI-${{github.ref_name}}-MacOS-${{ matrix.arch }}.zip
          directory: build/macos/Build/Products/Release
          path: TumblrAI.app
      - name: Release to github
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        with:
          tag_name: ${{github.ref_name}}
          files: package/TumblrAI-${{github.ref_name}}-MacOS-${{ matrix.arch }}.zip
